src/objects/Action_Plans_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Set the basic settings for My Action Plans App</description>
    <fields>
        <fullName>Chatter_Object_Brag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Enable Chatter Object Brag when a New Action Plan for this object is created.</description>
        <inlineHelpText>Enable Chatter Object Brag when a New Action Plan for this object is created.</inlineHelpText>
        <label>Enable Chatter Object Brag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unassigned_Task_Default__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If the Task is Unassigned in the Template, and this is Checked, the assigned User for the Task is the Owner of the Record. If this setting is unchecked, the assigned User for the Task is the Current User.</inlineHelpText>
        <label>Unassigned Task Defaults to Record Owner</label>
        <type>Checkbox</type>
    </fields>
    <label>Action Plans Settings</label>
</CustomObject>

src/objects/ActionPlan__c.object
<CustomObject>
    <description>Action Plan instance.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Action Plans</relationshipLabel>
        <relationshipName>Action_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Action_Plan__c</fullName>
        <label>Action Plan</label>
        <referenceTo>ActionPlan__c</referenceTo>
        <relationshipName>Action_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>R00NR0000000VZZ8MAO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>R00NR0000000VZZDMA4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>R00NR0000000VZZIMA4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SkipDay__c</fullName>
        <label>Skip Day</label>
        <picklist>
            <controllingField>SkipWeekends__c</controllingField>
            <picklistValues>
                <fullName>Friday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monday</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SkipWeekends__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Skip weekends when calculation activity start dates.</description>
        <label>Skip Weekends</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TaskRecordTypeID__c</fullName>
        <label>TaskRecordTypeID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Action Plan</label>
    <nameField>
        <label>Action Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ActionPlanTemplate__c.object
<CustomObject>
    <description>Template for Action Plan</description>
    <fields>
        <fullName>SkipDay__c</fullName>
        <description>If a Due Date lands on a weekend it should be pushed to this day.</description>
        <label>Skip Day</label>
        <picklist>
            <picklistValues>
                <fullName>Friday</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monday</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SkipWeekends__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If selected, tasks included in an Action Plan will not be given a Due Date that falls on a weekend.</description>
        <inlineHelpText>If selected, tasks included in an Action Plan will not be given a Due Date that falls on a weekend.</inlineHelpText>
        <label>Skip Weekends</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TaskRecordTypeID__c</fullName>
        <label>Task Record Type ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Action Plan Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plan Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/APTaskTemplate__c.object
<CustomObject>
    <description>Action Plan Task detail</description>
    <fields>
        <fullName>APTaskTemplate__c</fullName>
        <label>Task Dependency</label>
        <referenceTo>APTaskTemplate__c</referenceTo>
        <relationshipLabel>AP Tasks</relationshipLabel>
        <relationshipName>R00NR0000000VcWbMAK</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Action_Plan__c</fullName>
        <label>Action Plan</label>
        <referenceTo>ActionPlan__c</referenceTo>
        <relationshipName>R00NR0000000VccFMAS</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DaysFromStart__c</fullName>
        <label>Days</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dependent__c</fullName>
        <label>Dependent</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Minutes_Reminder__c</fullName>
        <label>Minutes Reminder</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reminder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reminder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SendEmail__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Send Email Notification of Task creation.</description>
        <label>SendEmail</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Misc</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00NR0000000Vd7NMAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>AP Task</label>
    <nameField>
        <label>APTaskTemplate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AP Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/APTTaskTemplate__c.object
<CustomObject>
    <description>Action Plan Template Task detail</description>
    <fields>
        <fullName>APTTaskTemplate__c</fullName>
        <label>Task Dependency</label>
        <referenceTo>APTTaskTemplate__c</referenceTo>
        <relationshipLabel>APT Task Templates</relationshipLabel>
        <relationshipName>R00NR0000000VaVDMA0</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Action_Plan_Template__c</fullName>
        <label>Action Plan Template</label>
        <referenceTo>ActionPlanTemplate__c</referenceTo>
        <relationshipLabel>APT Task Templates</relationshipLabel>
        <relationshipName>apTasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DaysFromStart__c</fullName>
        <inlineHelpText>test</inlineHelpText>
        <label>Days After</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dependent__c</fullName>
        <label>Dependent</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Minutes_Reminder__c</fullName>
        <label>Minutes Reminder</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reminder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reminder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SendEmail__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Send email notification when a Task is created.</description>
        <label>Send Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Misc</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00NR0000000Vd65MAC</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>APT Task</label>
    <nameField>
        <label>APT Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>APT Task Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/tests/ActionPlansUtilitiesTest.cls
/*
Action Plans v4
David Schach 2021

BSD 3-Clause License

Copyright (c) 2021, salesforce.com, inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

*/

@IsTest
private class ActionPlansUtilitiesTest {

	@TestSetup
	static void makeData(){
		Action_Plans_Settings__c aps = Action_Plans_Settings__c.getOrgDefaults();
		aps.Chatter_Object_Brag__c = true;
		aps.Unassigned_Task_Default__c = true;
		try{
			upsert aps;
		} catch (Exception e){
			update aps;
		}
	}

	@IsTest
	static void testDebugParameters(){
		Test.setCurrentPage(Page.ActionPlanCreation);
		Test.startTest();
		ActionPlanCreationController apcc = new ActionPlanCreationController(new ApexPages.StandardController( new ActionPlan__c() ) );
		ActionPlansTestUtilities.showDebugParameters = true;
		ActionPlansTestUtilities.debugParameters('testDebugParameters');
		Test.stopTest();
		System.assert(true);
	}

	@IsTest
	private static void testSaveMethod() {

		ActionPlansTestUtilities testutil =  new ActionPlansTestUtilities();
		ActionPlan__c ap = testutil.createNewActionPlan( 'account', 0 );

		List<APTaskTemplate__c> aptl = new List<APTaskTemplate__c>();
		for(Integer i = 0 ; i < 3; i++){
			aptl.add(makeAppTask(ap));
         }
         insert aptl;

		Test.startTest();

		ApexPages.currentPage().getParameters().put( 'refType', 'Account' );
		ApexPages.currentPage().getParameters().put( 'refId',  ap.Account__c);

		ActionPlanCreationController apcc = new ActionPlanCreationController(new ApexPages.StandardController( ap) );
		apcc.apTasks = aptl;

		System.assert(apcc.hasRelatedObject(), 'Should be a related object Account');

		apcc.save();

		ActionPlan__c rap = [SELECT Id FROM ActionPlan__c WHERE Id = :ap.Id];
		System.assert( rap != null );

		Test.stopTest();

	}

	@IsTest
	private static void testSaveMultiple() {

		ActionPlansTestUtilities testutil =  new ActionPlansTestUtilities();
		ActionPlan__c ap = testutil.createNewActionPlan( 'account', 0 );

		List<APTaskTemplate__c> aptl = new List<APTaskTemplate__c>();
		for(Integer i = 0 ; i < 3; i++){
			aptl.add(makeAppTask(ap));
        }
        insert aptl;

		Test.startTest();

		ap.SkipWeekends__c = true;
		ap.SkipDay__c = 'End of previous week';
		update ap;
		Test.setCurrentPage(Page.ActionPlanCreation);
		ApexPages.currentPage().getParameters().put( 'refType', 'Account' );
		ApexPages.currentPage().getParameters().put( 'refId',  ap.Account__c);
		ActionPlanCreationController apcc = new ActionPlanCreationController(new ApexPages.StandardController( ap) );
		apcc.apTasks = aptl;
		apcc.saveMultiple();
		ActionPlan__c rap = [SELECT Id, Account__c FROM ActionPlan__c WHERE Id = :ap.Id];
		System.assert( rap.Account__c == ap.Account__c );

		Test.stopTest();
	}

	@IsTest
	private static void testAccount(){
		testObject('Account');
	}

	@IsTest
	private static void testContact(){
		testObject('Contact');
	}

	@IsTest
	private static void testLead(){
		testObject('Lead');
	}

	@IsTest
	private static void testCase(){
		testObject('Case');
	}

	@IsTest
	private static void testCampaign(){
		testObject('Campaign');
	}

	@IsTest
	private static void testContract(){
		testObject('Contract');
	}

	private static void testObject(String objectName){
		Test.setCurrentPage(Page.ActionPlanCreation);

		ActionPlansTestUtilities testutil =  new ActionPlansTestUtilities();
		ActionPlanTemplate__c apt = testutil.createNewActionPlanTemplate( 5 );

		Test.startTest();

		ActionPlan__c ap = testutil.createNewActionPlan( objectName, 3 );

		ApexPages.currentPage().getParameters().put( 'refType', objectName );
		ApexPages.currentPage().getParameters().put( 'templateId', null );

		ActionPlanCreationController apcc = new ActionPlanCreationController(new ApexPages.StandardController( ap ) );

		apcc.save();

		ApexPages.currentPage().getParameters().put( 'templateId', apt.Id );
		apcc = new ActionPlanCreationController( new ApexPages.StandardController(new ActionPlan__c() ));
		apcc.apTasks = apcc.getAPTasks();

		apcc.save();

		System.assert( !apcc.apTasks.isEmpty() );

		Test.stopTest();

	}

	@IsTest
	private static void testCancel() {
		Test.startTest();

		Test.setCurrentPage(Page.ActionPlanCreation);

		ActionPlanCreationController apcc = new ActionPlanCreationController(new ApexPages.StandardController( new ActionPlan__c() ) );
		PageReference page = apcc.cancel();
		System.assert( page != null, 'Cancel page is null. Unexpected.' );

		ActionPlansTestUtilities testutil =  new ActionPlansTestUtilities();

		ActionPlan__c ap = testutil.createNewActionPlan( 'account', 0 );
		ApexPages.currentPage().getParameters().put( 'refType', 'Account' );
		ApexPages.currentPage().getParameters().put( 'refId',  ap.Account__c + ',' + testutil.createNewAccount().id);
		page = apcc.cancel();
		System.assert( page!= null );

		testutil.createNewActionPlan( 'contact', 0 );
		ApexPages.currentPage().getParameters().put( 'refType', 'Contact' );
		ApexPages.currentPage().getParameters().put( 'refId',  ap.Contact__c + ',' + testutil.createNewContact().id);
		page = apcc.cancel();
		System.assert( page!= null );

		testutil.createNewActionPlan( 'lead', 0 );
		ApexPages.currentPage().getParameters().put( 'refType', 'Lead' );
		ApexPages.currentPage().getParameters().put( 'refId',  ap.Lead__c + ',' + testutil.createNewLead().id);
		page = apcc.cancel();
		System.assert( page!= null );

		testutil.createNewActionPlan( 'opportunity', 0 );
		ApexPages.currentPage().getParameters().put( 'refType', 'Opportunity' );
		ApexPages.currentPage().getParameters().put( 'refId',  ap.Opportunity__c + ',' + testutil.createNewOpportunity().id);
		page = apcc.cancel();
		System.assert( page!= null );

		testutil.createNewActionPlan( 'account', 0 );
		ApexPages.currentPage().getParameters().put( 'refType', 'Account' );
		ApexPages.currentPage().getParameters().put( 'refId',  ap.Account__c);
		page = apcc.cancel();
		System.assert( page!= null );

		ActionPlanTemplate__c apt = testutil.createNewActionPlanTemplate( 0 );
		ApexPages.currentPage().getParameters().put( 'templateId', apt.Id );
		page = apcc.cancel();
		System.assert( page!= null );
		Test.stopTest();
	}

	@IsTest
	private static void testRelatedObjectId() {
		Test.startTest();

		ActionPlansTestUtilities testutil =  new ActionPlansTestUtilities();

		ActionPlan__c ap = testutil.createNewActionPlan( 'account', 0 );
		ActionPlanCreationController apcc = new ActionPlanCreationController(new ApexPages.StandardController( ap ) );
		Id recId = apcc.relatedObjectId();
		System.assert( ap.Account__c == recId);

		ap = testutil.createNewActionPlan( 'contact', 0 );
		apcc = new ActionPlanCreationController(new ApexPages.StandardController( ap ) );
		recId = apcc.relatedObjectId();
		System.assert( ap.Contact__c == recId);

		ap = testutil.createNewActionPlan( 'lead', 0 );
		apcc = new ActionPlanCreationController(new ApexPages.StandardController( ap ) );
		recId = apcc.relatedObjectId();
		System.assert( ap.Lead__c == recId);

		ap = testutil.createNewActionPlan( 'opportunity', 0 );
		apcc = new ActionPlanCreationController(new ApexPages.StandardController( ap ) );
		recId = apcc.relatedObjectId();
		System.assert( ap.Opportunity__c == recId);
	}

	@IsTest
	private static void testDeleteActionPlans() {

		ActionPlansTestUtilities testutil =  new ActionPlansTestUtilities();
		System.runAs(new User(Id = UserInfo.getUserId())){
			testutil.assignAPPermissionSets(UserInfo.getUserId(), false);
		}
		ActionPlan__c ap = testutil.createNewActionPlan( 'account', 0 );
		ActionPlan__c ap2 = testutil.createNewActionPlan( 'account', 0 );
		List<ActionPlan__c> lAp = new List<ActionPlan__c>();
		lAp.add(ap);
		lAp.add(ap2);
		String url = 'testURL';
		String records = ap.Id + ',' + ap2.id;

		Test.startTest();
		Test.setCurrentPage(Page.ActionPlanDetail);
		ActionPlanDetailController apdc = new ActionPlanDetailController(new ApexPages.StandardController( ap ) );
		ApexPages.currentPage().getParameters().put('retURL', url);
		ApexPages.currentPage().getParameters().put('records', records);
		PageReference page = apdc.deletePlan();
		Test.stopTest();

		List<ActionPlan__c> lAp2 = [SELECT Id FROM ActionPlan__c WHERE Id IN :lAp];
		System.assert(lAp2.size() == 1);
		if( !ActionPlansUtilities.getIsLex() ){
			System.assertEquals(page.getUrl(), url);
		}
	}

	@IsTest
	private static void doChatterPost() {

		ActionPlansTestUtilities.showDebugParameters = false;

		Action_Plans_Settings__c aps = Action_Plans_Settings__c.getInstance();
		if(!aps.Chatter_Object_Brag__c){
			aps.Chatter_Object_Brag__c = true;
			update aps;
		}
		System.assert(aps.Chatter_Object_Brag__c);

		Test.startTest();

		Test.setCurrentPage(Page.ActionPlanCreation);
		ActionPlansTestUtilities testutil =  new ActionPlansTestUtilities();
		for(String k : ActionPlansTestUtilities.standardObjects){

			switch on k {
				when 'account'{
					Account a = testutil.createNewAccount();
					ApexPages.currentPage().getParameters().put( 'refId', a.Id );
				}
				when 'lead'{
					Lead c = testutil.createNewLead();
					ApexPages.currentPage().getParameters().put( 'refId', c.Id );
				}
				when 'contract'{
					Contract c = testutil.createNewContract();
					ApexPages.currentPage().getParameters().put( 'refId', c.Id );
				}
				when 'campaign'{
					Campaign c = testutil.createNewCampaign();
					ApexPages.currentPage().getParameters().put( 'refId', c.Id );
				}
				when 'opportunity'{
					Opportunity c = testutil.createNewOpportunity();
					ApexPages.currentPage().getParameters().put( 'refId', c.Id );
				}
				when 'contact'{
					Contact c = testutil.createNewContact();
					ApexPages.currentPage().getParameters().put( 'refId', c.Id );
				}
				when 'case'{
					Case c = testutil.createNewCase();
					ApexPages.currentPage().getParameters().put( 'refId', c.Id );
				}
			}

			ActionPlanTemplate__c apt = testutil.createNewActionPlanTemplate( 5 );
			for(APTTaskTemplate__c aptt : apt.apTasks__r){

				aptt.User__c = null;
			}
			update apt.apTasks__r;

			apt.TaskRecordTypeID__c = ActionPlansTestUtilities.getNonDefaultAvailableTaskRecordType();
			apt.SkipWeekends__c = true;
			apt.SkipDay__c = 'End of previous week';

			update apt;

			ApexPages.currentPage().getParameters().put( 'id', null );

			ApexPages.currentPage().getParameters().put( 'templateId', apt.Id );
			ActionPlanCreationController apcc = new ActionPlanCreationController( new Apexpages.StandardController( new ActionPlan__c() ) );
			apcc.refreshRelatedObjectsLookUp();

			apcc.actionPlan.SkipWeekends__c = true;
			apcc.actionPlan.SkipDay__c = 'End of previous week';
			apcc.getTasks();

			System.assert( !apcc.getTasks().isEmpty() );

			apcc.save();
		}

		Test.stopTest();

		System.assertEquals(ActionPlansTestUtilities.standardObjects.size(), [SELECT Count() FROM ActionPlan__c]);
	}

	@IsTest
	private static void testbatchIds(){

		ActionPlansTestUtilities apTestUtil = new ActionPlansTestUtilities();

		System.assert( apTestUtil.batchIds('account') != null );
	}

	@IsTest
	private static void testRandomWord(){

		ActionPlansTestUtilities testUtil = new ActionPlansTestUtilities();

		System.assert( testUtil.createRandomWord('testword') != testUtil.createRandomWord() );
	}

	private static APTaskTemplate__c makeAppTask ( ActionPlan__c ap ){

		ActionPlansTestUtilities testutil =  new ActionPlansTestUtilities();
		APTaskTemplate__c at   = new APTaskTemplate__c();
		at.Action_Plan__c      = ap.Id;
		at.Dependent__c        = 'None';
		at.DaysFromStart__c    = 2.0;
		at.User__c             = testutil.createTestUser().Id;
		at.SendEmail__c        = false;
		at.Subject__c          = 'Test ';
		at.Type__c             = 'Email';
		at.Priority__c         = 'Low';
		at.Comments__c         = 'Test';
		at.Reminder__c         = true;
		at.Minutes_Reminder__c = '510';
		return at;
	}

}