src/objects/ActionPlan__c.object
<CustomObject>
    <description>Action Plan instance.</description>
    <fields>
        <fullName>Action_Plan__c</fullName>
        <label>Action Plan</label>
        <referenceTo>ActionPlan__c</referenceTo>
        <relationshipName>Action_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Action Plan</label>
    <nameField>
        <label>Action Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/APTaskTemplate__c.object
<CustomObject>
    <description>Action Plan Task detail</description>
    <fields>
        <fullName>APTaskTemplate__c</fullName>
        <label>Task Dependency</label>
        <referenceTo>APTaskTemplate__c</referenceTo>
        <relationshipLabel>AP Tasks</relationshipLabel>
        <relationshipName>R00NR0000000VcWbMAK</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Action_Plan__c</fullName>
        <label>Action Plan</label>
        <referenceTo>ActionPlan__c</referenceTo>
        <relationshipName>R00NR0000000VccFMAS</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DaysFromStart__c</fullName>
        <label>Days</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dependent__c</fullName>
        <label>Dependent</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Minutes_Reminder__c</fullName>
        <label>Minutes Reminder</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reminder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reminder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SendEmail__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Send Email Notification of Task creation.</description>
        <label>SendEmail</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Misc</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00NR0000000Vd7NMAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>AP Task</label>
    <nameField>
        <label>APTaskTemplate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AP Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/tests/ActionPlansBatchDeleteTest.cls
/*
Action Plans v4
David Schach 2021

Action Plans v3
Force.com Labs 2011
http://appexchange.salesforce.com/listingDetail?listingId=a0N30000003HcINEA0

BSD 3-Clause License

Copyright (c) 2021, salesforce.com, inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
@IsTest
private class ActionPlansBatchDeleteTest {

    @IsTest
	private static void testDelete() {

		Test.startTest();

		ActionPlansTestUtilities aptu = new ActionPlansTestUtilities();
		ActionPlan__c ap =   aptu.createNewActionPlan('account',1);

		Set<Id> sIDs = new Set<Id>();
		sIDs.add(ap.Id);

		ActionPlansBatchDelete taskBatch = new ActionPlansBatchDelete(sIDs);
		Database.ExecuteBatch( taskBatch );

		Test.stopTest();

		System.assert([SELECT Id FROM ActionPlan__c].isEmpty());
	}

	@IsTest
	private static void testFutureDelete() {

		Test.startTest();

		ActionPlansTestUtilities aptu = new ActionPlansTestUtilities();
		ActionPlan__c ap =   aptu.createNewActionPlan('account',1);

		Set<Id> sIDs = new Set<Id>();
		sIDs.add(ap.Id);

		delete ap;

		Test.stopTest();

		System.assert([SELECT Id FROM ActionPlan__c].isEmpty());
	}

	@IsTest
	private static void testDeleteException() {

		Test.startTest();

		ActionPlansTestUtilities.forceError = true;

		ActionPlansTestUtilities aptu = new ActionPlansTestUtilities();
		ActionPlan__c ap =   aptu.createNewActionPlan('account',1);

		Set<Id> sIDs = new Set<Id>();
		sIDs.add(ap.Id);

		ActionPlansBatchDelete taskBatch = new ActionPlansBatchDelete(sIDs);
		Database.ExecuteBatch( taskBatch );

		Test.stopTest();

		System.assert([SELECT Id FROM ActionPlan__c].isEmpty());
	}

    @IsTest
	private static void testUnDelete() {

		Test.startTest();

		ActionPlansTestUtilities aptu = new ActionPlansTestUtilities();
		ActionPlan__c ap = aptu.createNewActionPlan('account',1);

		APTaskTemplate__c at = new APTaskTemplate__c();
		at.Action_Plan__c 	 = ap.Id;
		at.Dependent__c		 = 'None';
		at.DaysFromStart__c  = 2.0;
		at.User__c			 = Userinfo.getUserId();
		at.SendEmail__c		 = false;
		at.Subject__c		 = 'Test ';
		at.Type__c			 = 'Email';
		at.Priority__c		 = 'Low';
		at.Comments__c		 = 'Test';
		at.Reminder__c		 = true;
		at.Minutes_Reminder__c = '510';
		insert at;

		at = new APTaskTemplate__c();
		at.Action_Plan__c 	 = ap.Id;
		at.Dependent__c		 = 'None';
		at.DaysFromStart__c  = 2.0;
		at.User__c			 = Userinfo.getUserId();
		at.SendEmail__c		 = true;
		at.Subject__c		 = 'Test ';
		at.Type__c			 = 'Email';
		at.Priority__c		 = 'Low';
		at.Comments__c		 = 'Test';
		at.Reminder__c		 = true;
		at.Minutes_Reminder__c = '510';
		insert at;

		Task x 				= new Task();
		x.Priority 			= at.Priority__c;
		x.TaskAPTaskTemplate__c	= at.Id;
		x.Subject			= at.Subject__c;
		insert x;

		Set<Id> sIDs = new Set<Id>();
		sIDs.add(ap.Id);

		ActionPlansBatchDelete taskBatch = new ActionPlansBatchDelete(sIDs);
		Database.ExecuteBatch( taskBatch );

		Test.stopTest();
		undelete ap;

		System.assert(![SELECT Id FROM ActionPlan__c].isEmpty());

	}
}