src/objects/ActionPlan__c.object
<CustomObject>
    <description>Action Plan instance.</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Action Plans</relationshipLabel>
        <relationshipName>Action_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Action_Plan__c</fullName>
        <label>Action Plan</label>
        <referenceTo>ActionPlan__c</referenceTo>
        <relationshipName>Action_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Action Plans</relationshipLabel>
        <relationshipName>Action_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Action Plans</relationshipLabel>
        <relationshipName>Action_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>R00NR0000000VZZ8MAO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Action Plans</relationshipLabel>
        <relationshipName>Action_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>R00NR0000000VZZDMA4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>R00NR0000000VZZIMA4</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Action Plan</label>
    <nameField>
        <label>Action Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/APTaskTemplate__c.object
<CustomObject>
    <description>Action Plan Task detail</description>
    <fields>
        <fullName>APTaskTemplate__c</fullName>
        <label>Task Dependency</label>
        <referenceTo>APTaskTemplate__c</referenceTo>
        <relationshipLabel>AP Tasks</relationshipLabel>
        <relationshipName>R00NR0000000VcWbMAK</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Action_Plan__c</fullName>
        <label>Action Plan</label>
        <referenceTo>ActionPlan__c</referenceTo>
        <relationshipName>R00NR0000000VccFMAS</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ActivityDate__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Dependent__c</fullName>
        <label>Dependent</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Minutes_Reminder__c</fullName>
        <label>Minutes Reminder</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reminder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reminder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SendEmail__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Send Email Notification of Task creation.</description>
        <label>SendEmail</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting on someone else</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Misc</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00NR0000000Vd7NMAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>AP Task</label>
    <nameField>
        <label>APTaskTemplate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AP Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ActionPlansBatchTaskBuilder.cls
/**
* Create the Batch process for std Task inserts
* @author Sebastian Muñoz
*/
global with sharing class ActionPlansBatchTaskBuilder implements Database.Batchable<SObject>, Database.Stateful{
    
    private List<APTaskTemplate__c> apTasks             { get; set; }
    private List<String>            aptIds              { get; set; }
    private List<Task>              myTasksWithOutEmail { get; set; }
    private List<Task>              myTasksWithEmail    { get; set; }
    
    /**
    * Constructor
    */
    public ActionPlansBatchTaskBuilder( List<String> apttIds ){
        this.aptIds = apttIds;
    }
    
    /**
    * QueryLocator: Select the List of APTaskTemplate__c.
    */
    global Database.QueryLocator start( Database.BatchableContext bc ){
        //Add Action Plan custom object reference Field.
        String soql = 'Select a.User__c, a.Type__c, a.Subject__c, a.Status__c, a.SendEmail__c, a.Reminder__c, a.Minutes_Reminder__c,'+
                      'a.Priority__c, a.Name, a.Id, a.Dependent__c, a.Comments__c, a.ActivityDate__c,'+
                      'a.Action_Plan__c, a.Action_Plan__r.Account__c , a.Action_Plan__r.Contact__c, '+
                      'a.Action_Plan__r.Campaign__c , a.Action_Plan__r.Case__c , a.Action_Plan__r.Contract__c, '+
                      'a.Action_Plan__r.Lead__c, a.Action_Plan__r.Opportunity__c, '+
                      'a.APTaskTemplate__c From APTaskTemplate__c a Where a.Id IN ';
        String inClause = '(';
        for( String iter : this.aptIds ){
            inClause += '\'' + iter + '\',';
        }             
        inClause = inClause.substring( 0, inClause.length() - 1 );
        inClause += ')';
        soql += inClause;
        
        return Database.getQueryLocator( soql );
    }
    
    /**
    *
    * @param bc
    * @param data
    */
    global void execute( Database.BatchableContext bc, List<SObject> data ){
        
        this.myTasksWithEmail       = new List<Task>();
        this.myTasksWithOutEmail    = new List<Task>();
        this.apTasks                = new List<APTaskTemplate__c>();
        
        for( SObject obj : data ){
               APTaskTemplate__c oneData = ( APTaskTemplate__c )obj;
               this.apTasks.add( oneData );
        }

        //Now run this magic!
        for( APTaskTemplate__c apTask : this.apTasks ){
            
            // check if task exists already
            Task t = new Task();
            t.Subject           = apTask.Subject__c;
            t.Priority          = apTask.Priority__c;
            t.OwnerId           = apTask.User__c;
            t.TaskTemplateId__c = apTask.Id; 
                
            // fake link to AP Task Template
            if( apTask.Comments__c != null ){
                t.Description = apTask.Comments__c;
            } 
            
            //set reminder based on user's default reminder setting
            if( apTask.Reminder__c == true && apTask.ActivityDate__c != null ){
                
                t.isReminderSet = apTask.Reminder__c;
                
                t.ReminderDateTime = Datetime.newInstance( apTask.ActivityDate__c.year(), apTask.ActivityDate__c.month(), apTask.ActivityDate__c.day(), 0, 0, 0 );
                t.ReminderDateTime = t.ReminderDateTime.addMinutes( Integer.valueOf( apTask.Minutes_Reminder__c ) );                          
            }              
                
            //link to Action Plan's Related To Object
            if( apTask.Action_Plan__r.Account__c != null ){
                t.WhatId = apTask.Action_Plan__r.Account__c;
            } 
            
            if( apTask.Action_Plan__r.Contact__c != null ){
                t.WhoId = apTask.Action_Plan__r.Contact__c;
            } 
            
            if( apTask.Action_Plan__r.Lead__c != null ){
                t.WhoId = apTask.Action_Plan__r.Lead__c;
            } 
            
            if( apTask.Action_Plan__r.Opportunity__c != null ){
                t.WhatId = apTask.Action_Plan__r.Opportunity__c;
            } 
            
            //Add new version Support to Cases , Contracts ans Campaigns
            if( apTask.Action_Plan__r.Campaign__c != null ){
                t.WhatId = apTask.Action_Plan__r.Campaign__c;
            } 
            
            if( apTask.Action_Plan__r.Case__c != null ){
                t.WhatId = apTask.Action_Plan__r.Case__c;
            }
            
            if( apTask.Action_Plan__r.Contract__c != null ){
                t.WhatId = apTask.Action_Plan__r.Contract__c;
            } 
            //Add here code sample to extend for a custom Object
            /*
            if( apTask.Action_Plan__r.CustomObject__c != null ){
                t.WhatId = apTask.Action_Plan__r.CustonObject__c;
            } 
            */
            
            t.Type          = apTask.Type__c;
            t.Status        = 'Not Started';
            t.ActivityDate  = apTask.ActivityDate__c;  
            
            if( apTask.Dependent__c == 'None' ){
	            if( apTask.SendEmail__c == true ){
	                this.myTasksWithEmail.add( t ); 
	            }
	            else{
	                this.myTasksWithOutEmail.add( t ); 
	            }
            }
        }
    
        Database.DMLOptions dmlo    = new Database.DMLOptions();
        Database.DMLOptions dmlo2   = new Database.DMLOptions();
        
        if( this.myTasksWithEmail.size() > 0 ){
            dmlo.EmailHeader.triggerUserEmail = true;
            database.insert( this.myTasksWithEmail, dmlo );
        }
        
        if( this.myTasksWithOutEmail.size() > 0 ){
            dmlo2.EmailHeader.triggerUserEmail = false;
            database.insert( this.myTasksWithOutEmail, dmlo2 );
        }
    }
    
    /**
    *
    */
    global void finish( Database.BatchableContext bc ){
    
    }
}