src/objects/ActionPlan__c.object
<CustomObject>
    <description>Action Plan instance.</description>
    <fields>
        <fullName>Action_Plan_Template__c</fullName>
        <label>Action Plan Template</label>
        <referenceTo>ActionPlanTemplate__c</referenceTo>
        <relationshipName>R00NR0000000VbUtMAK</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Action_Plan__c</fullName>
        <label>Action Plan</label>
        <referenceTo>ActionPlan__c</referenceTo>
        <relationshipName>Action_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TaskRecordTypeID__c</fullName>
        <label>TaskRecordTypeID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Action Plan</label>
    <nameField>
        <label>Action Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ActionPlanTemplate__c.object
<CustomObject>
    <description>Template for Action Plan</description>
    <fields>
        <fullName>TaskRecordTypeID__c</fullName>
        <label>Task Record Type ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Action Plan Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plan Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Activity.object
<CustomObject>
</CustomObject>

force-app/main/default/objects/Activity/fields/TaskAPTaskTemplate__c.field-meta.xml
<CustomField>
    <fullName>TaskAPTaskTemplate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ActionPlans - replaces old Id field now that custom lookups on Activities are available</description>
    <label>AP Task Template</label>
    <referenceTo>APTaskTemplate__c</referenceTo>
    <relationshipLabel>Template Tasks</relationshipLabel>
    <relationshipName>Template_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/APTaskTemplate__c.object
<CustomObject>
    <description>Action Plan Task detail</description>
    <fields>
        <fullName>APTaskTemplate__c</fullName>
        <label>Task Dependency</label>
        <referenceTo>APTaskTemplate__c</referenceTo>
        <relationshipLabel>AP Tasks</relationshipLabel>
        <relationshipName>R00NR0000000VcWbMAK</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Action_Plan__c</fullName>
        <label>Action Plan</label>
        <referenceTo>ActionPlan__c</referenceTo>
        <relationshipName>R00NR0000000VccFMAS</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ActivityDate__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DaysFromStart__c</fullName>
        <label>Days</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dependent__c</fullName>
        <label>Dependent</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Minutes_Reminder__c</fullName>
        <label>Minutes Reminder</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reminder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reminder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SendEmail__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Send Email Notification of Task creation.</description>
        <label>SendEmail</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting on someone else</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_Reminder__c</fullName>
        <formula>IF(Reminder__c ,IF(MOD(FLOOR(VALUE(Minutes_Reminder__c) / 60),12) == 0,&apos;12&apos;,TEXT(MOD(FLOOR(VALUE(Minutes_Reminder__c) / 60),12))) &amp; &apos;:&apos; &amp; IF(MOD(VALUE(Minutes_Reminder__c) ,60)==0,&apos;00&apos;,TEXT(MOD(VALUE(Minutes_Reminder__c) ,60)))+&apos; &apos;+ IF( VALUE(Minutes_Reminder__c)&gt;=720, &apos;PM&apos;,&apos;AM&apos;),&apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Time Reminder</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Misc</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00NR0000000Vd7NMAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>taskIndex__c</fullName>
        <label>taskIndex</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>AP Task</label>
    <nameField>
        <label>APTaskTemplate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AP Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ActionPlanDetailController.cls
/*
Action Plans v4
Updated by David Schach 2021


Action Plans v3
Force.com Labs 2011
http://appexchange.salesforce.com/listingDetail?listingId=a0N30000003HcINEA0

BSD 3-Clause License

Copyright (c) 2021, salesforce.com, inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

*/
public inherited sharing class ActionPlanDetailController{

	private ActionPlan__c            actionPlan;
	public Boolean                  hasRecordType   { get; set; }

	/**
	* Constructor
	*/
	public ActionPlanDetailController( ApexPages.StandardController stdController ){

		this.actionPlan = ( ActionPlan__c ) stdController.getRecord();

		System.debug('constructor actionplanId ' + this.actionPlan.Id);

		this.hasRecordType = ActionPlansUtilities.HAS_RECORD_TYPE;
	}

	/**
	* Deletes the current Action Plan loaded and redirects to the AP Template List
	* @return newPage
	*/
	public PageReference deletePlan(){

		System.debug('retURL: ' + ApexPages.currentPage().getParameters().get('retURL'));

		Savepoint sp        	= Database.setSavepoint();
		//ActionPlan__c ap    = actionPlan;
		//Set<Id> recordIds	= new Set<Id>{actionPlan.Id};

		//delete ap, which will also delete apts via master-detail relationship
		try{

			//ActionPlansBatchDeleteUtilities taskBatch = new ActionPlansBatchDeleteUtilities(recordIds);
			//taskBatch.deleteActionPlans();

			delete actionPlan;

		} catch( Exception e ){
			Database.rollback( sp );
		}
		String retURL = '/' + ActionPlansUtilities.getObjectKeyPrefix( 'ActionPlan__c' ) + '/o' ;

		String theme = UserInfo.getUiThemeDisplayed();

		if(ApexPages.currentPage().getParameters().get('templateId') != null){
			retUrl = '/' + ApexPages.currentPage().getParameters().get('templateId');
		}
		else if(ApexPages.currentPage().getParameters().get('retURL') != null && (theme == 'Theme2' || theme == 'Theme3')){
			retURL = ApexPages.currentPage().getParameters().get('retURL');
		}
		// Send the user to the tab.
		PageReference newPage = new PageReference( retURL );
		newPage.setRedirect( true );

		return newPage;
	}

	/**
	* Gets all tasks for a given ActionPlan
	*/
	private List<APTaskTemplate__c> apTasks;

	public List<APTaskTemplate__c> getTasks(){

		System.debug('existing apTasks ' + this.aptasks);
		if( apTasks == null || apTasks.isEmpty() ) {
			apTasks = [SELECT Action_Plan__c, ActivityDate__c, APTaskTemplate__c, APTaskTemplate__r.Subject__c, Comments__c, DaysFromStart__c, Dependent__c, Id,
							IsClosed__c, Minutes_Reminder__c, Name, Priority__c, Reminder__c, Time_Reminder__c, SendEmail__c, Status__c, Subject__c, Task_RecordTypeId__c,
							TaskIndex__c, Type__c, User__c, User__r.Name, (SELECT Id, Subject FROM Template_Tasks__r)
							FROM APTaskTemplate__c WHERE Action_Plan__c = :actionPlan.Id ORDER BY TaskIndex__c ASC];
		}
		return apTasks;
	}

	/**
	* Returns number of completed tasks
	*/
	public Integer getCompleted(){
		if(actionPlan.Id == null){ return 0; }

		List<APTaskTemplate__c> ts = [SELECT t.Id
				FROM APTaskTemplate__c t
				WHERE t.Status__c IN :ActionPlansUtilities.getClosedTaskStatuses()
				AND t.ActivityDate__c != null AND t.Action_Plan__c = :actionPlan.Id];

		return ( ts != null ) ? ts.size() : 0;
	}

	/**
	* Checks if Action Plan Template has been changed since the creation of the Action Plan.
	* @return Boolean
	*/
	public Boolean getVersion(){
		if( actionPlan.Action_Plan_Template__c != null ){
			ActionPlanTemplate__c TempApt = [SELECT LastModifiedDate FROM ActionPlanTemplate__c WHERE Id = :actionPlan.Action_Plan_Template__c];
			if( TempApt.LastModifiedDate > actionPlan.createdDate ){
				return true;
			}
		}
		return false;
	}

	public String getRelatedObjectLabel(){

		String objLabel='';

		for( String f : ActionPlansUtilities.getCustomRelationshipFields() ){

			if(actionPlan.get(f) != null){
				Id objId = (Id)actionPlan.get(f);
				Schema.DescribeSObjectResult dsr = objId.getSObjectType().getDescribe();
				objLabel = dsr.getLabel();
				break;
			}
		}

		return objLabel;
	}


	public String getrelatedRecordName(){

		System.debug(actionPlan);

		String objName='';
		Id objId;

		for( String f : ActionPlansUtilities.getCustomRelationshipFields() ){
			//System.debug('evaluating string ' + f + ' value ' + actionPlan.get(f));

			if(actionPlan.get(f) != null){
				objId = (Id)actionPlan.get(f);
				//System.debug('we have a value objId ' + objId);
				Schema.DescribeSObjectResult dsr = objId.getSObjectType().getDescribe();
				objName = dsr.getName();
				//System.debug('object name is ' + objName);
				break;
			} else {
				System.debug('no value in field ' + f);
			}
		}



		switch on objName {
			when 'Case' {
				Case c = [SELECT Id, Subject, CaseNumber FROM Case WHERE Id = :objId LIMIT 1];
				return c.CaseNumber + ': ' + c.Subject;
			}
			when 'Contract' {
				Contract c = [SELECT Id, ContractNumber FROM Contract WHERE Id = :objId LIMIT 1];
				return c.ContractNumber;
			}
			when else {
				String relNameQuery = 'SELECT Id, Name FROM ' + objName + ' WHERE Id = \'' + objId + '\'';
				System.debug('relNameQuery ' + relNameQuery);
				SObject so = Database.query(relNameQuery)[0];

				return (String)so.get('Name');
			}
		}
	}

	/**
	 * Convert Record Type Id to Record Type Name
	 * @return Record Type Name
	 */
	public String getRecordTypeName(){
		String toReturn = '';
		if(ActionPlansUtilities.HAS_RECORD_TYPE){
			Map<Id,Schema.RecordTypeInfo> rtMapById = Task.SObjectType.getDescribe().getRecordTypeInfosById();
			if(!rtMapById.isEmpty() && rtMapById.containsKey(actionPlan.TaskRecordTypeID__c)){
				return rtMapById.get(actionPlan.TaskRecordTypeID__c).getName();
			}
		}
		return toReturn;
	}

}