src/objects/ActionPlan__c.object
<CustomObject>
    <description>Action Plan instance.</description>
    <label>Action Plan</label>
    <nameField>
        <label>Action Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/APTaskTemplate__c.object
<CustomObject>
    <description>Action Plan Task detail</description>
    <fields>
        <fullName>APTaskTemplate__c</fullName>
        <label>Task Dependency</label>
        <referenceTo>APTaskTemplate__c</referenceTo>
        <relationshipLabel>AP Tasks</relationshipLabel>
        <relationshipName>R00NR0000000VcWbMAK</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>AP Task</label>
    <nameField>
        <label>APTaskTemplate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AP Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/SectionHeaderControllerTest.cls
/**
 * Action Plans v4
 * Updated by David Schach 2021
 */
@IsTest
private class SectionHeaderControllerTest {

	@IsTest
	static void testObjectTabDescribe(){
		ActionPlansTestUtilities testUtil = new ActionPlansTestUtilities();
		User u = testUtil.createTestUser();

		Test.startTest();
		System.runAs(u){
			SectionHeaderController shc = new SectionHeaderController();
			shc.objectName = 'ActionPlan__c';
			shc.getIsCustom();
			shc.getObjectIconInfo();

			shc.objectName = 'APTaskTemplate__c';
			shc.getIsCustom();
			shc.getObjectIconInfo();

			shc.objectName = 'Account';
			shc.getIsCustom();
			shc.getObjectIconInfo();
		}
		Test.stopTest();

	}
}